account:
  uin: 你的QQ号
  password: '你的QQ密码'
default-middlewares: &default
  access-token: '302178580f001e14884538a395804f5c'
servers:
  - http:
      disabled: true
      host: 0.0.0.0
      port: 5700
      middlewares:
        <<: *default
      post:
        - url: 'http://host.docker.internal:6780'
          secret: '6d07a9efdb5c3f68d8769818719983bf'

  - ws:
      disabled: false
      host: 0.0.0.0
      port: 6700
      middlewares:
        <<: *default

  - ws-reverse:
      disabled: true
      api: ws://host.docker.internal:6700/api
      event: ws://host.docker.internal:6700/event
      reconnect-interval: 3000
      middlewares:
        <<: *default
